export interface Tool {
  id: string;
  name: string;
  description: string;
  category: "developer" | "text" | "math" | "ai" | "image";
  iconName: string;
  hotkey: string;
  tags: string[];
  isPopular?: boolean;
  isNew?: boolean;
  usageCount?: number;
}

export const CATEGORIES = [
  { id: "all", name: "All Tools", icon: "LayoutGrid" },
  { id: "developer", name: "Developer Tools", icon: "Code2" },
  { id: "text", name: "Text Tools", icon: "FileText" },
  { id: "math", name: "Math Tools", icon: "Calculator" },
  { id: "ai", name: "AI Tools", icon: "Sparkles" },
  { id: "image", name: "Image Tools", icon: "Image" },
];

export const TOOLS: Tool[] = [
  // --- DEVELOPER TOOLS ---
  {
    id: "json-formatter",
    name: "JSON Formatter & Validator",
    description: "Format, beautify, validate, and minify raw JSON with error highlighting.",
    category: "developer",
    iconName: "Braces",
    hotkey: "J",
    tags: ["json", "format", "beautify", "minify", "validate", "lint", "developer"],
    isPopular: true,
    usageCount: 1240,
  },
  {
    id: "base64",
    name: "Base64 Encoder & Decoder",
    description: "Easily encode text to Base64 or decode Base64 back to readable text.",
    category: "developer",
    iconName: "Binary",
    hotkey: "B",
    tags: ["base64", "encode", "decode", "binary", "text", "developer"],
    usageCount: 840,
  },
  {
    id: "jwt-inspector",
    name: "JWT Token Inspector",
    description: "Decode and inspect JSON Web Tokens (JWT) to view header, payload, and claims.",
    category: "developer",
    iconName: "ShieldAlert",
    hotkey: "W",
    tags: ["jwt", "token", "decode", "inspect", "header", "payload", "auth", "developer"],
    isPopular: true,
    isNew: true,
    usageCount: 620,
  },
  {
    id: "uuid-generator",
    name: "UUID Bulk Generator",
    description: "Generate single or bulk cryptographically secure UUIDs (v4).",
    category: "developer",
    iconName: "Fingerprint",
    hotkey: "U",
    tags: ["uuid", "guid", "generator", "random", "id", "bulk", "developer"],
    usageCount: 910,
  },
  {
    id: "hash-generator",
    name: "Cryptographic Hash Generator",
    description: "Generate MD5, SHA-1, SHA-256, and SHA-512 hashes instantly from input text.",
    category: "developer",
    iconName: "Hash",
    hotkey: "H",
    tags: ["hash", "md5", "sha256", "sha1", "sha512", "crypto", "security", "developer"],
    usageCount: 730,
  },
  {
    id: "color-picker",
    name: "Color Palette & Gradient",
    description: "Pick colors, generate CSS gradients, and copy hex/rgb/hsl codes seamlessly.",
    category: "developer",
    iconName: "Palette",
    hotkey: "C",
    tags: ["color", "picker", "gradient", "palette", "css", "hex", "rgb", "hsl", "design"],
    isPopular: true,
    usageCount: 1120,
  },

  // --- TEXT TOOLS ---
  {
    id: "word-counter",
    name: "Word & Character Counter",
    description: "Count words, characters, sentences, paragraphs, and estimate reading time.",
    category: "text",
    iconName: "FileText",
    hotkey: "O",
    tags: ["word", "character", "counter", "reading-time", "text", "letters", "statistics"],
    usageCount: 1350,
  },
  {
    id: "case-converter",
    name: "Text Case Converter",
    description: "Convert text instantly between UPPERCASE, lowercase, Title Case, camelCase, and more.",
    category: "text",
    iconName: "Type",
    hotkey: "A",
    tags: ["case", "converter", "uppercase", "lowercase", "titlecase", "sentence", "text"],
    usageCount: 780,
  },
  {
    id: "text-compare",
    name: "Text Difference Checker",
    description: "Compare two text documents side-by-side to highlight differences and lines changes.",
    category: "text",
    iconName: "Columns2",
    hotkey: "D",
    tags: ["diff", "compare", "text", "difference", "merge", "checker", "side-by-side"],
    isPopular: true,
    isNew: true,
    usageCount: 950,
  },
  {
    id: "text-cleaner",
    name: "Text Line Organizer",
    description: "Clean text by sorting lines, removing duplicates, stripping extra spaces, and reversing.",
    category: "text",
    iconName: "Brush",
    hotkey: "E",
    tags: ["cleaner", "sort", "reverse", "remove-duplicates", "text", "lines", "format"],
    usageCount: 540,
  },

  // --- MATH TOOLS ---
  {
    id: "calculator",
    name: "Scientific Calculator",
    description: "Complete mathematical calculations with basic arithmetic, trigonometry, and logarithms.",
    category: "math",
    iconName: "CalculatorIcon",
    hotkey: "M",
    tags: ["calculator", "math", "scientific", "trig", "algebra", "numbers"],
    isPopular: true,
    usageCount: 1620,
  },
  {
    id: "unit-converter",
    name: "Universal Unit Converter",
    description: "Convert values across length, weight, temperature, speed, area, and volume.",
    category: "math",
    iconName: "Scale",
    hotkey: "V",
    tags: ["converter", "unit", "length", "weight", "temperature", "metric", "imperial", "math"],
    usageCount: 1040,
  },
  {
    id: "percentage-calculator",
    name: "Percentage Calculator",
    description: "Easily find percentage increases, decreases, fractions, and standard X% of Y.",
    category: "math",
    iconName: "Percent",
    hotkey: "P",
    tags: ["percentage", "percent", "math", "calculator", "increase", "decrease", "ratio"],
    usageCount: 680,
  },
  {
    id: "age-calculator",
    name: "Accurate Age Calculator",
    description: "Calculate your precise age down to years, months, days, minutes, and seconds.",
    category: "math",
    iconName: "CalendarDays",
    hotkey: "G",
    tags: ["age", "birthday", "calculator", "date", "time", "difference", "days"],
    isNew: true,
    usageCount: 410,
  },

  // --- AI TOOLS ---
  {
    id: "ai-summarizer",
    name: "AI Smart Summarizer",
    description: "Leverage Gemini AI to extract key insights, summarize documents, or create bullet points.",
    category: "ai",
    iconName: "Sparkles",
    hotkey: "S",
    tags: ["ai", "summarize", "insights", "text", "document", "gemini", "smart"],
    isPopular: true,
    usageCount: 2310,
  },
  {
    id: "ai-translator",
    name: "AI Multi-Language Translator",
    description: "Context-aware high-fidelity AI translation with language auto-detection.",
    category: "ai",
    iconName: "Languages",
    hotkey: "T",
    tags: ["ai", "translate", "language", "translator", "spanish", "french", "gemini", "multilingual"],
    usageCount: 1840,
  },
  {
    id: "ai-code-explainer",
    name: "AI Code Explainer",
    description: "Paste a code snippet and receive a highly detailed, line-by-line interactive explanation.",
    category: "ai",
    iconName: "Cpu",
    hotkey: "X",
    tags: ["ai", "code", "explain", "programming", "javascript", "python", "gemini", "learn"],
    isNew: true,
    usageCount: 1470,
  },
  {
    id: "ai-regex",
    name: "AI RegEx Generator",
    description: "Convert normal language instructions into complex regular expression patterns instantly.",
    category: "ai",
    iconName: "Regex",
    hotkey: "R",
    tags: ["ai", "regex", "pattern", "expression", "match", "gemini", "string"],
    usageCount: 980,
  },

  // --- IMAGE TOOLS ---
  {
    id: "image-compressor",
    name: "Client-Side Image Compressor",
    description: "Compress images directly in your browser with adjustable quality levels to shrink file size.",
    category: "image",
    iconName: "FileImage",
    hotkey: "I",
    tags: ["image", "compress", "shrink", "quality", "png", "jpg", "jpeg", "webp", "client-side"],
    isPopular: true,
    usageCount: 1530,
  },
  {
    id: "image-resizer",
    name: "Instant Image Resizer",
    description: "Resize images to custom width/height dimensions or keep aspect ratio constraints.",
    category: "image",
    iconName: "Crop",
    hotkey: "K",
    tags: ["image", "resize", "crop", "aspect-ratio", "dimensions", "png", "jpg", "scale"],
    usageCount: 890,
  },
  {
    id: "palette-extractor",
    name: "Image Palette Extractor",
    description: "Upload an image to automatically analyze and extract its core dominant color palette.",
    category: "image",
    iconName: "EyeDropper",
    hotkey: "Y",
    tags: ["image", "color", "palette", "extractor", "designer", "contrast", "dominant"],
    isNew: true,
    usageCount: 710,
  },
];
